version: '3'

services:
  databaseAuthentication:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mynet
    volumes:
      - dbdataa:/var/lib/mysql
  authenticationMigration:
    image: authenticationmigration
    environment:
      - DATABASE_URL=databaseAuthentication
    networks:
      - mynet
  authentication:
    image: authentication
    environment:
      - DATABASE_URL=databaseAuthentication
    ports:
      - 5000:5000
    networks:
      - mynet
  some-redis:
    image: redis
    networks:
      - mynet
#    ports:
#      - 6379:6379
  databaseElections:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mynet
    volumes:
      - dbdatae:/var/lib/mysql
  electionsMigration:
    image: electionsmigration
    environment:
      - DATABASE_URL=databaseElections
    networks:
      - mynet
  admin:
    image: admin
    environment:
      - DATABASE_URL=databaseElections
    ports:
      - 5001:5001
    networks:
      - mynet
  daemon:
    image: daemon
    environment:
      - DATABASE_URL=databaseElections
      - REDIS_URL=some-redis
    networks:
      - mynet
  user:
    image: user
    environment:
      - REDIS_URL=some-redis
    ports:
      - 5002:5002
    networks:
      - mynet
    deploy:
      replicas: 3
volumes:
  dbdataa:
  dbdatae:

networks:
  mynet:
    driver: overlay